#!/usr/bin/env python3
"""Where the unavoidable same-finger collisions land, and what tiering moves.

Usage: python3 tools/collision_report.py > thecore/collision-report.md

Part A enumerates, for every layout of issue #27, the same-finger
different-key pairs under 1v1 replay data with the direction pair each one
lands on.  Part B re-runs the optimizer with `--direction-tiers` on and
compares.  Everything uses the functions of tools/thecore_svalboard.py; this
script writes no HTML and touches no committed artifact.
"""
import collections
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import thecore_svalboard as ts  # noqa: E402

W = 0.5
CLASSES = ["centre-edge", "adjacent-edges", "opposite-edges", "same-direction"]
TIER_SETS = [(0.5, 1.0, 1.5), (0.7, 1.0, 1.3), (0.3, 1.0, 2.0)]
# Same ratios as 0.3/1.0/2.0 but scaled up, so the tier mean is no longer well
# below 1.0 (issue #28 review): this separates a steep spread from a shrunken
# same-finger term weighed against the untouched zone term.
SCALE_SETS = [(0.5, 1.0, 1.5), (0.7, 1.0, 1.3),
              (0.3, 1.0, 2.0), (0.6, 2.0, 4.0), (1.5, 5.0, 10.0),
              (3.0, 10.0, 20.0)]
TOP = 15


def sep(n):
    """A markdown header separator row of n columns."""
    return "|%s|" % ("|".join([" --- "] * n))


def slot_name(slots, i):
    s = slots[i]
    return "%s %s, %s" % (s["finger"], s["pos"], s["plane"])


def collisions(place, slots, pairs):
    """Undirected same-finger different-key pairs: (rate, class, cross, a, b)."""
    agg = collections.defaultdict(float)
    for (a, b), rate in pairs.items():
        if a not in place or b not in place or a == b:
            continue
        if slots[place[a]]["finger"] != slots[place[b]]["finger"]:
            continue
        agg[tuple(sorted((a, b)))] += rate
    rows = []
    for (a, b), rate in agg.items():
        sa, sb = slots[place[a]], slots[place[b]]
        rows.append((rate, ts.direction_class(sa["pos"], sb["pos"]),
                     sa["plane"] != sb["plane"], a, b))
    rows.sort(key=lambda r: (-r[0], r[3], r[4]))
    return rows


def effective_multiplier(place, slots, pairs, tiers):
    """Rate-weighted mean tier multiplier over one layout's collisions.

    The scalar that actually rescales the same-finger term: a tier set is
    only "neutral" against the untouched zone term if this lands near 1.0,
    and it is dominated by the EASY value because centre-edge carries about
    70% of the collision mass.
    """
    num = den = 0.0
    for rate, cls, _cross, _a, _b in collisions(place, slots, pairs):
        num += rate * tiers[{"same-direction": 0, "centre-edge": 0,
                             "adjacent-edges": 1, "opposite-edges": 2}[cls]]
        den += rate
    return num / den


def class_totals(rows):
    tot = collections.defaultdict(float)
    for rate, cls, cross, _a, _b in rows:
        tot[cls] += rate
        if cross:
            tot["any-cross-plane"] += rate
    return tot


def totals_row(label, rows):
    tot = class_totals(rows)
    return "| %s | %s | %.2f |" % (
        label, " | ".join("%.2f" % tot[c] for c in CLASSES + ["any-cross-plane"]),
        sum(tot[c] for c in CLASSES))


def pair_table(rows, slots, place, limit=TOP):
    out = ["| rate /min | key A | slot A | key B | slot B | class | planes |",
           "| --- | --- | --- | --- | --- | --- | --- |"]
    for rate, cls, cross, a, b in rows[:limit]:
        out.append("| %.2f | %s | %s | %s | %s | %s | %s |"
                   % (rate, ts.label(a), slot_name(slots, place[a]),
                      ts.label(b), slot_name(slots, place[b]), cls,
                      "cross-plane" if cross else "same plane"))
    return "\n".join(out)


def moved_table(slots, a_place, b_place, load):
    moved = sorted((k for k in a_place if a_place[k] != b_place[k]),
                   key=lambda k: -load.get(k, 0.0))
    if not moved:
        return "No key moved.\n"
    out = ["| TheCore key | flat slot | tiered slot | load /min |",
           "| --- | --- | --- | --- |"]
    for k in moved:
        out.append("| %s | %s | %s | %.2f |"
                   % (ts.label(k), slot_name(slots, a_place[k]),
                      slot_name(slots, b_place[k]), load.get(k, 0.0)))
    return "\n".join(out) + "\n"


def main():
    with open(os.path.join(ts.HERE, ts.SUMMARY), encoding="utf-8") as f:
        summary = json.load(f)
    with open(os.path.join(ts.HERE, ts.COOP), encoding="utf-8") as f:
        coop = json.load(f)
    slots = ts.build_slots()

    print("# Where the same-finger collisions land, and what tiering moves"
          " (issue #28)\n")
    print("Generated by `tools/collision_report.py`. Part 1 of issue #28 only:")
    print("the diagnostic and the tiered-cost experiment. No merge decision")
    print("here, and no committed artifact is regenerated on this branch.\n")
    print("## Method\n")
    print("* Layouts come from the same three input sets as")
    print("  `thecore/coop-blend-report.md`: 1v1-only, raw 50/50 co-op blend,")
    print("  and normalized 50/50 (`--coop-normalize`, the committed layout).")
    print("  All three appear in Part A. Part B re-optimizes only the")
    print("  1v1-only and the normalized 50/50 inputs, the two the issue #27")
    print("  decision is actually choosing between; the raw blend is a")
    print("  diagnostic waypoint and is not re-run with tiers.")
    print("* Collisions are always measured on **1v1 bigram rates**, whatever")
    print("  data built the layout, so the three layouts are comparable. A")
    print("  collision is a bigram whose two TheCore keys are different and")
    print("  sit on the same finger; the two orders of a pair are summed.")
    print("  Class totals are raw rates, so they run a hair above the flat")
    print("  same-finger cost term, which halves the cross-plane pairs (for")
    print("  the 1v1-only 5.0 layout, 29.89 raw against 29.83 costed: half of")
    print("  the 0.12 that is cross-plane).")
    print("* Direction-pair classes, on the five positions of one finger:")
    print("  **centre-edge** one key is the centre; **adjacent-edges** two")
    print("  different edges that are not opposite (e.g. north and inward);")
    print("  **opposite-edges** north/south or inward/outward, a travel")
    print("  reversal; **same-direction** the same position in both planes,")
    print("  which needs no finger movement at all. Plane is reported")
    print("  alongside: **any-cross-plane** counts every pair whose two keys")
    print("  are on different planes, and overlaps the four direction classes.")
    print("* The tiered cost (`--direction-tiers EASY,MED,HARD`) replaces the")
    print("  flat 1.0 same-plane multiplier with EASY for centre-edge and")
    print("  same-direction, MED for adjacent-edges, HARD for opposite-edges.")
    print("  The existing 0.5 cross-plane factor still multiplies on top.")
    print("  With the flag off the tool is byte-identical (sanity checks).\n")
    print("## What it found\n")
    print("* The flat optimizer already puts most collision mass on the")
    print("  easiest class. In every layout centre-edge carries 20.9-24.2 of")
    print("  the ~30-32 per minute. Opposite-edges is under 1/min in four of")
    print("  the six layouts, but 1.88/min in both raw 50/50 layouts.")
    print("* On the **1v1-only** inputs tiering still helps, and cheaply. Both")
    print("  files: 7-9 keys move, adjacent-edges drops 8.11 -> 6.27/min,")
    print("  opposite-edges 0.82 -> 0.69 (5.0) and 0.88 -> 0.69 (6.0), and")
    print("  the total collision rate falls too (29.89 -> 29.16, 30.28 ->")
    print("  29.55). Under the original flat objective the tiered layout")
    print("  costs +0.10 - a tenth of a percent. The move is the same for")
    print("  0.5/1.0/1.5 and 0.7/1.0/1.3.")
    print("* On the **normalized 50/50** inputs tiering changes nothing at")
    print("  all: 0 keys move at every tier setting, for both files. That")
    print("  layout is already a fixed point of the pairwise-swap hill climb")
    print("  under the tiered cost - a local optimum, not a proven global")
    print("  one, since the search only ever tries single swaps. Its higher")
    print("  1v1 same-finger rate")
    print("  (32.2 vs 29.8, issue #27) is not misplaced direction pairs, it")
    print("  is extra centre-edge mass (23.96 vs 20.85/min on 5.0).")
    print("* The extreme setting 0.3/1.0/2.0 is a trap, and the reason is")
    print("  its scale, not its steepness. Multipliers only touch the")
    print("  same-finger term, and centre-edge carries ~70% of the collision")
    print("  mass, so EASY=0.3 discounts the whole same-finger term to an")
    print("  effective 0.54 against an untouched zone term: the optimizer")
    print("  then swaps the two heaviest keys between middle and ring to buy")
    print("  cheaper slots, paying about 6/min of extra collisions (35.76/min")
    print("  on 5.0, 36.15 on 6.0) for 1.7-1.8 of zone difficulty, +4.1 under")
    print("  the flat objective. Scale the same 0.3 : 1.0 : 2.0 ratio up to")
    print("  0.6/2.0/4.0 or 1.5/5.0/10.0 and the trap vanishes: those")
    print("  reproduce the mild-tier layout exactly on both files. See the")
    print("  scale check under each file's Part B.\n")

    stable = {}
    for name, rel in ts.FILES:
        keys = ts.read_file(os.path.join(ts.HERE, rel))
        ts.exclude(keys)
        l1, p1, _ = ts.replay_load(summary, rel)
        lc, pc = ts.coop_load(coop, rel)
        lraw, praw = ts.mix(l1, lc, W), ts.mix(p1, pc, W)
        lcn, pcn = ts.normalized(l1, p1, lc, pc)
        lnorm, pnorm = ts.mix(l1, lcn, W), ts.mix(p1, pcn, W)
        inputs = [("1v1-only", l1, p1), ("raw 50/50", lraw, praw),
                  ("normalized 50/50", lnorm, pnorm)]
        flat = {n: ts.assign(dict(keys), lo, po, slots, [])[0]
                for n, lo, po in inputs}

        print("# %s\n" % name)
        print("## Part A: collisions under 1v1 data\n")
        for n, _lo, _po in inputs:
            rows = collisions(flat[n], slots, p1)
            print("### %s layout: %d colliding pairs\n" % (n, len(rows)))
            print(pair_table(rows, slots, flat[n]))
            print()
        print("### Class totals, rate /min (%s)\n" % name)
        print("| layout | %s | any-cross-plane | all |"
              % " | ".join(CLASSES))
        print(sep(len(CLASSES) + 3))
        for n, _lo, _po in inputs:
            print(totals_row(n, collisions(flat[n], slots, p1)))
        print()

        print("## Part B: the optimizer with tiers on\n")
        for lname, lo, po in (inputs[0], inputs[2]):
            print("### %s inputs\n" % lname)
            base = flat[lname]
            bsame, bzone = ts.cost(base, slots, lo, po)
            print("Flat-cost layout, flat objective: %.2f same-finger +"
                  " %.2f zone = %.2f.\n" % (bsame, bzone, bsame + bzone))
            print("| tiers (easy/med/hard) | keys moved vs flat |"
                  " tiered objective | flat objective of the tiered layout"
                  " (flat layout: %.2f) | 1v1 same-finger /min (flat layout:"
                  " %.2f) |" % (bsame + bzone,
                                ts.cost(base, slots, l1, p1)[0]))
            print("| --- | --- | --- | --- | --- |")
            places = {}
            for t in TIER_SETS:
                pl = ts.assign(dict(keys), lo, po, slots, [], list(t))[0]
                places[t] = pl
                ts_same, ts_zone = ts.cost(pl, slots, lo, po, list(t))
                fs, fz = ts.cost(pl, slots, lo, po)
                moved = sum(1 for k in base if base[k] != pl[k])
                print("| %.1f/%.1f/%.1f | %d | %.2f | %.2f (%+.2f) | %.2f |"
                      % (t + (moved, ts_same + ts_zone, fs + fz,
                              fs + fz - bsame - bzone,
                              ts.cost(pl, slots, l1, p1)[0])))
            print()
            print("Collision classes under 1v1 data, rate /min:\n")
            print("| layout | %s | any-cross-plane | all |"
                  % " | ".join(CLASSES))
            print(sep(len(CLASSES) + 3))
            print(totals_row("flat", collisions(base, slots, p1)))
            for t in TIER_SETS:
                print(totals_row("tiers %.1f/%.1f/%.1f" % t,
                                 collisions(places[t], slots, p1)))
            print()
            for t in TIER_SETS:
                print("Keys that moved, tiers %.1f/%.1f/%.1f vs flat:\n" % t)
                print(moved_table(slots, base, places[t], lo))
            common = [k for k in base
                      if len({places[t][k] for t in TIER_SETS}) == 1]
            flips = sorted(set(base) - set(common),
                           key=lambda k: -lo.get(k, 0.0))
            print("Placements identical across all three tier settings:"
                  " %d of %d keys.\n" % (len(common), len(base)))
            if flips:
                print("| key that differs between tier settings | %s |"
                      % " | ".join("tiers %.1f/%.1f/%.1f" % t
                                   for t in TIER_SETS))
                print(sep(len(TIER_SETS) + 1))
                for k in flips:
                    print("| %s | %s |"
                          % (ts.label(k),
                             " | ".join(slot_name(slots, places[t][k])
                                        for t in TIER_SETS)))
                print()
            if lname == "1v1-only":
                print("#### Is 0.3/1.0/2.0 bad because it is steep, or"
                      " because it is small?\n")
                print("Because it is small. The tier multipliers only touch")
                print("the same-finger term; the zone-difficulty term is")
                print("untouched. What rescales one against the other is the")
                print("rate-weighted mean multiplier over the collisions the")
                print("layout actually has (the *effective* column below).")
                print("Centre-edge carries about 70% of the mass, so that")
                print("number follows EASY, not the plain mean: 0.3/1.0/2.0")
                print("has a plain mean of 1.10 but an effective 0.54, i.e.")
                print("same-finger work at nearly half price, and the")
                print("optimizer starts buying collisions to save slot")
                print("difficulty. The last four rows share the ratio")
                print("0.3 : 1.0 : 2.0 and differ only in scale, which is the")
                print("test: scale the same steep ratio up and the trap")
                print("disappears, so the hazard is the scale, not the")
                print("spread. All figures are flat-objective, so they are")
                print("comparable:\n")
                print("| tiers | effective x on the flat layout |"
                      " keys moved vs flat | flat same-finger"
                      " | flat zone | flat total | same layout as"
                      " 0.5/1.0/1.5? |")
                print(sep(7))
                mild = places[TIER_SETS[0]]
                for t in SCALE_SETS:
                    pl = ts.assign(dict(keys), lo, po, slots, [], list(t))[0]
                    fs, fz = ts.cost(pl, slots, lo, po)
                    print("| %s | %.2f | %d | %.2f | %.2f | %.2f | %s |"
                          % ("/".join("%.1f" % v for v in t),
                             effective_multiplier(base, slots, po, t),
                             sum(1 for k in base if base[k] != pl[k]),
                             fs, fz, fs + fz,
                             "yes" if pl == mild else "no"))
                print()
            stable[(name, lname)] = (len(common), len(base), flips)

    print("""# Conclusion

Tiering does move the unavoidable collisions onto easier direction pairs, but
only on the 1v1-only inputs, and the gain is small because the flat optimizer
was already close. On both hotkey files the tiered 1v1-only layout takes the
same seven-to-nine-key rearrangement at 0.5/1.0/1.5 and at 0.7/1.0/1.3: the
two heaviest ring keys trade centre and south, the ring inward key goes to
north, and a middle/ring pair of north and outward keys swap fingers. That
takes 1.84/min off adjacent edges and 0.13/min (5.0) or 0.19/min (6.0) off
opposite edges. Only part of it lands on centre-edge, which rises 1.23 (5.0)
and 1.35 (6.0); the remaining ~0.5-0.6/min stops being a same-finger
transition at all, which is the better outcome of the two. So it is not a
trade: the total collision rate falls as well, and the price under the
original flat objective is +0.10 on a total near 99, about 0.1%.

On the normalized 50/50 inputs - the layout committed on `agent/issue-27` -
tiering is a no-op at all three tier settings and both files. Nothing moves:
that layout is already a fixed point of the hill climb under the tiered cost.
(A fixed point of single swaps, not a proven optimum; a search that could move
three keys at once might still find something.)
So the #27 finding that normalizing raises the 1v1 same-finger rate from
29.8 to 32.2/min cannot be answered by better direction placement: the extra
2.4/min is already sitting on centre-edge rolls, the cheapest class there is.
If that regression matters, it has to be paid for somewhere other than the
direction tiers.

The tier weights matter little, but the hazard is not where it first looks.
0.5/1.0/1.5 and 0.7/1.0/1.3 give byte-identical placements; 38 of 40 keys are
also common to 0.3/1.0/2.0, which differs only by swapping the two heaviest
keys (5.0: O and I; 6.0: J and I) between the middle and ring centre slots,
and that one flip is what makes 0.3/1.0/2.0 worse on every measure but its
own objective. The cause is scale, not spread. The tiers multiply the
same-finger term and nothing else, so a tier set whose rate-weighted effective
multiplier sits well under 1.0 quietly marks same-finger work down against an
untouched zone-difficulty term, and the optimizer sells collisions for slot
difficulty: at 0.3/1.0/2.0 the effective multiplier is 0.54 and it buys 1.7
(5.0) to 1.8 (6.0) of zone difficulty for about 6/min of extra collisions.
Hold the ratio and raise the scale - 0.6/2.0/4.0, 1.5/5.0/10.0 - and the
identical steep ratio reproduces the mild-tier layout exactly on both files.
So a steep spread is fine; a set that discounts the classes carrying the mass
is not. Since centre-edge carries about 70% of the collisions, EASY is what
sets that effective multiplier, and keeping it near 1.0 (or raising MED and
HARD to compensate) is the practical rule.

One caveat the numbers cannot cover: the tier ordering itself
(centre-edge easy, adjacent-edges medium, opposite-edges hard) is an
assumption about finger mechanics, the same kind as `FINGER_WEIGHT`. Part 2
of issue #28 goes looking for evidence for it in the Discord distillations.
""")
    print("""# Sanity checks

* **Flag off is byte-identical.** `python3 tools/thecore_svalboard.py` with no
  flags, before and after this branch's edit, gives identical stdout (sha1
  88d0a96359ec0c085f919885e6f93ec3a3da5155) and identical
  `thecore/svalboard-keymap.html` (sha1
  d0d74a38d255c2f014de1f21476d837a913fbcad, the same sha
  `thecore/coop-blend-report.md` records for the flag-off page).
* **Both co-op blends are byte-identical too.** `--coop-blend 0.5` (page sha1
  576d46051332880eb695531b6dcd3bc5a1c534d6) and `--coop-blend 0.5
  --coop-normalize` (892b70c18cb7e3b783f1df4b5a752dbd4d7d4670, the committed
  page) match their pre-edit stdout and HTML exactly.
* **No committed artifact was regenerated.** Every run above wrote the page to
  the worktree and was reverted with `git checkout --`; the branch changes
  only `tools/thecore_svalboard.py`, adds `tools/collision_report.py` and this
  report.
* **Determinism.** `--direction-tiers 0.5,1.0,1.5` run under
  `PYTHONHASHSEED=5` and `PYTHONHASHSEED=77` produced byte-identical stdout
  (sha1 391d4cf890a2a7413cb759bea47d15b29e96ba0a) and byte-identical HTML
  (089dc6d8152d76086b1b0a8259473e5d926bebc1). This report, generated under
  `PYTHONHASHSEED=5` and `PYTHONHASHSEED=99`, is byte-identical as well.
* **Script agrees with the CLI.** The tiered objective this report computes
  for the 0.5/1.0/1.5 1v1-only layouts (88.49 and 87.36) is the `final cost`
  line the tool itself prints under the same flag.
* **Known debt.** A page generated with `--direction-tiers` records nothing
  about the flag in its lede, unlike `--coop-blend`, which stamps the blend
  into the page. Harmless today because no tiered page is committed anywhere,
  but a tiered page would be indistinguishable from a flat one; stamp the
  lede before committing any tiered artifact.
* **Placed counts unchanged.** 40 keys placed per file in every layout and
  every tier setting, and the tiered runs pass the tool's `EXPECTED_UNPLACED`
  guard unchanged.
""")


if __name__ == "__main__":
    main()
