#!/usr/bin/env python3
"""Where the unavoidable same-finger collisions land, and what tiering moves.

Usage: python3 tools/collision_report.py > thecore/collision-report.md

Part A enumerates, for every layout of issue #27, the same-finger
different-key pairs under 1v1 replay data with the direction pair each one
lands on.  Part B re-runs the optimizer with `--direction-tiers` on and
compares.  Everything uses the functions of tools/thecore_svalboard.py; this
script writes no HTML and touches no committed artifact.
"""
import collections
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import thecore_svalboard as ts  # noqa: E402

W = 0.5
CLASSES = ["centre-edge", "adjacent-edges", "opposite-edges", "same-direction"]
TIER_SETS = [(0.5, 1.0, 1.5), (0.7, 1.0, 1.3), (0.3, 1.0, 2.0)]
TOP = 15


def slot_name(slots, i):
    s = slots[i]
    return "%s %s, %s" % (s["finger"], s["pos"], s["plane"])


def collisions(place, slots, pairs):
    """Undirected same-finger different-key pairs: (rate, class, cross, a, b)."""
    agg = collections.defaultdict(float)
    for (a, b), rate in pairs.items():
        if a not in place or b not in place or a == b:
            continue
        if slots[place[a]]["finger"] != slots[place[b]]["finger"]:
            continue
        agg[tuple(sorted((a, b)))] += rate
    rows = []
    for (a, b), rate in agg.items():
        sa, sb = slots[place[a]], slots[place[b]]
        rows.append((rate, ts.direction_class(sa["pos"], sb["pos"]),
                     sa["plane"] != sb["plane"], a, b))
    rows.sort(key=lambda r: (-r[0], r[3], r[4]))
    return rows


def class_totals(rows):
    tot = collections.defaultdict(float)
    for rate, cls, cross, _a, _b in rows:
        tot[cls] += rate
        if cross:
            tot["any-cross-plane"] += rate
    return tot


def totals_row(label, rows):
    tot = class_totals(rows)
    return "| %s | %s | %.2f |" % (
        label, " | ".join("%.2f" % tot[c] for c in CLASSES + ["any-cross-plane"]),
        sum(tot[c] for c in CLASSES))


def pair_table(rows, slots, place, limit=TOP):
    out = ["| rate /min | key A | slot A | key B | slot B | class | planes |",
           "| --- | --- | --- | --- | --- | --- | --- |"]
    for rate, cls, cross, a, b in rows[:limit]:
        out.append("| %.2f | %s | %s | %s | %s | %s | %s |"
                   % (rate, ts.label(a), slot_name(slots, place[a]),
                      ts.label(b), slot_name(slots, place[b]), cls,
                      "cross-plane" if cross else "same plane"))
    return "\n".join(out)


def moved_table(slots, a_place, b_place, load):
    moved = sorted((k for k in a_place if a_place[k] != b_place[k]),
                   key=lambda k: -load.get(k, 0.0))
    if not moved:
        return "No key moved.\n"
    out = ["| TheCore key | flat slot | tiered slot | load /min |",
           "| --- | --- | --- | --- |"]
    for k in moved:
        out.append("| %s | %s | %s | %.2f |"
                   % (ts.label(k), slot_name(slots, a_place[k]),
                      slot_name(slots, b_place[k]), load.get(k, 0.0)))
    return "\n".join(out) + "\n"


def main():
    with open(os.path.join(ts.HERE, ts.SUMMARY), encoding="utf-8") as f:
        summary = json.load(f)
    with open(os.path.join(ts.HERE, ts.COOP), encoding="utf-8") as f:
        coop = json.load(f)
    slots = ts.build_slots()

    print("# Where the same-finger collisions land, and what tiering moves"
          " (issue #28)\n")
    print("Generated by `tools/collision_report.py`. Part 1 of issue #28 only:")
    print("the diagnostic and the tiered-cost experiment. No merge decision")
    print("here, and no committed artifact is regenerated on this branch.\n")
    print("## Method\n")
    print("* Layouts come from the same three input sets as")
    print("  `thecore/coop-blend-report.md`: 1v1-only, raw 50/50 co-op blend,")
    print("  and normalized 50/50 (`--coop-normalize`, the committed layout).")
    print("* Collisions are always measured on **1v1 bigram rates**, whatever")
    print("  data built the layout, so the three layouts are comparable. A")
    print("  collision is a bigram whose two TheCore keys are different and")
    print("  sit on the same finger; the two orders of a pair are summed.")
    print("  Class totals are raw rates, so they run a hair above the flat")
    print("  same-finger cost term, which halves the cross-plane pairs (for")
    print("  the 1v1-only 5.0 layout, 29.89 raw against 29.83 costed: half of")
    print("  the 0.12 that is cross-plane).")
    print("* Direction-pair classes, on the five positions of one finger:")
    print("  **centre-edge** one key is the centre; **adjacent-edges** two")
    print("  different edges that are not opposite (e.g. north and inward);")
    print("  **opposite-edges** north/south or inward/outward, a travel")
    print("  reversal; **same-direction** the same position in both planes,")
    print("  which needs no finger movement at all. Plane is reported")
    print("  alongside: **any-cross-plane** counts every pair whose two keys")
    print("  are on different planes, and overlaps the four direction classes.")
    print("* The tiered cost (`--direction-tiers EASY,MED,HARD`) replaces the")
    print("  flat 1.0 same-plane multiplier with EASY for centre-edge and")
    print("  same-direction, MED for adjacent-edges, HARD for opposite-edges.")
    print("  The existing 0.5 cross-plane factor still multiplies on top.")
    print("  With the flag off the tool is byte-identical (sanity checks).\n")
    print("## What it found\n")
    print("* The flat optimizer already puts most collision mass on the")
    print("  easiest class. In every layout centre-edge carries 21-24 of the")
    print("  ~30-32 per minute, and opposite-edges under 1/min.")
    print("* On the **1v1-only** inputs tiering still helps, and cheaply. Both")
    print("  files: 7-9 keys move, adjacent-edges drops 8.11 -> 6.27/min,")
    print("  opposite-edges 0.82 -> 0.69 (5.0) and 0.88 -> 0.69 (6.0), and")
    print("  the total collision rate falls too (29.89 -> 29.16, 30.28 ->")
    print("  29.55). Under the original flat objective the tiered layout")
    print("  costs +0.10 - a tenth of a percent. The move is the same for")
    print("  0.5/1.0/1.5 and 0.7/1.0/1.3.")
    print("* On the **normalized 50/50** inputs tiering changes nothing at")
    print("  all: 0 keys move at every tier setting, for both files. That")
    print("  layout is already tier-optimal; its higher 1v1 same-finger rate")
    print("  (32.2 vs 29.8, issue #27) is not misplaced direction pairs, it")
    print("  is extra centre-edge mass (23.96 vs 20.85/min on 5.0).")
    print("* The extreme setting 0.3/1.0/2.0 is a trap: it swaps the two")
    print("  heaviest keys between middle and ring to buy centre-edge slots,")
    print("  which raises the total collision rate to 35.8/min and costs")
    print("  +4.1 under the flat objective. It buys nothing the milder tiers")
    print("  do not already buy.\n")

    stable = {}
    for name, rel in ts.FILES:
        keys = ts.read_file(os.path.join(ts.HERE, rel))
        ts.exclude(keys)
        l1, p1, _ = ts.replay_load(summary, rel)
        lc, pc = ts.coop_load(coop, rel)
        lraw, praw = ts.mix(l1, lc, W), ts.mix(p1, pc, W)
        lcn, pcn = ts.normalized(l1, p1, lc, pc)
        lnorm, pnorm = ts.mix(l1, lcn, W), ts.mix(p1, pcn, W)
        inputs = [("1v1-only", l1, p1), ("raw 50/50", lraw, praw),
                  ("normalized 50/50", lnorm, pnorm)]
        flat = {n: ts.assign(dict(keys), lo, po, slots, [])[0]
                for n, lo, po in inputs}

        print("# %s\n" % name)
        print("## Part A: collisions under 1v1 data\n")
        for n, _lo, _po in inputs:
            rows = collisions(flat[n], slots, p1)
            print("### %s layout: %d colliding pairs\n" % (n, len(rows)))
            print(pair_table(rows, slots, flat[n]))
            print()
        print("### Class totals, rate /min (%s)\n" % name)
        print("| layout | %s | any-cross-plane | all |"
              % " | ".join(CLASSES))
        print("| --- | --- | --- | --- | --- | --- | --- |")
        for n, _lo, _po in inputs:
            print(totals_row(n, collisions(flat[n], slots, p1)))
        print()

        print("## Part B: the optimizer with tiers on\n")
        for lname, lo, po in (inputs[0], inputs[2]):
            print("### %s inputs\n" % lname)
            base = flat[lname]
            bsame, bzone = ts.cost(base, slots, lo, po)
            print("Flat-cost layout, flat objective: %.2f same-finger +"
                  " %.2f zone = %.2f.\n" % (bsame, bzone, bsame + bzone))
            print("| tiers (easy/med/hard) | keys moved vs flat |"
                  " tiered objective | flat objective of the tiered layout"
                  " (flat layout: %.2f) | 1v1 same-finger /min (flat layout:"
                  " %.2f) |" % (bsame + bzone,
                                ts.cost(base, slots, l1, p1)[0]))
            print("| --- | --- | --- | --- | --- |")
            places = {}
            for t in TIER_SETS:
                pl = ts.assign(dict(keys), lo, po, slots, [], list(t))[0]
                places[t] = pl
                ts_same, ts_zone = ts.cost(pl, slots, lo, po, list(t))
                fs, fz = ts.cost(pl, slots, lo, po)
                moved = sum(1 for k in base if base[k] != pl[k])
                print("| %.1f/%.1f/%.1f | %d | %.2f | %.2f (%+.2f) | %.2f |"
                      % (t + (moved, ts_same + ts_zone, fs + fz,
                              fs + fz - bsame - bzone,
                              ts.cost(pl, slots, l1, p1)[0])))
            print()
            print("Collision classes under 1v1 data, rate /min:\n")
            print("| layout | %s | any-cross-plane | all |"
                  % " | ".join(CLASSES))
            print("| --- | --- | --- | --- | --- | --- | --- |")
            print(totals_row("flat", collisions(base, slots, p1)))
            for t in TIER_SETS:
                print(totals_row("tiers %.1f/%.1f/%.1f" % t,
                                 collisions(places[t], slots, p1)))
            print()
            for t in TIER_SETS:
                print("Keys that moved, tiers %.1f/%.1f/%.1f vs flat:\n" % t)
                print(moved_table(slots, base, places[t], lo))
            common = [k for k in base
                      if len({places[t][k] for t in TIER_SETS}) == 1]
            flips = sorted(set(base) - set(common),
                           key=lambda k: -lo.get(k, 0.0))
            print("Placements identical across all three tier settings:"
                  " %d of %d keys.\n" % (len(common), len(base)))
            if flips:
                print("| key that differs between tier settings | %s |"
                      % " | ".join("tiers %.1f/%.1f/%.1f" % t
                                   for t in TIER_SETS))
                print("| --- | --- | --- | --- |")
                for k in flips:
                    print("| %s | %s |"
                          % (ts.label(k),
                             " | ".join(slot_name(slots, places[t][k])
                                        for t in TIER_SETS)))
                print()
            stable[(name, lname)] = (len(common), len(base), flips)

    print("""# Conclusion

Tiering does move the unavoidable collisions onto easier direction pairs, but
only on the 1v1-only inputs, and the gain is small because the flat optimizer
was already close. On both hotkey files the tiered 1v1-only layout takes the
same seven-to-nine-key rearrangement at 0.5/1.0/1.5 and at 0.7/1.0/1.3: the
two heaviest ring keys trade centre and south, the ring inward key goes to
north, and a middle/ring pair of north and outward keys swap fingers. That
converts 1.84/min of adjacent-edge work into centre-edge work and shaves
0.13-0.19/min off the opposite-edge work. It is not a trade: the total
collision rate falls as well, and the price under the original flat objective
is +0.10 on a total near 99, about 0.1%.

On the normalized 50/50 inputs - the layout committed on `agent/issue-27` -
tiering is a no-op at all three tier settings and both files. Nothing moves.
So the #27 finding that normalizing raises the 1v1 same-finger rate from
29.8 to 32.2/min cannot be answered by better direction placement: the extra
2.4/min is already sitting on centre-edge rolls, the cheapest class there is.
If that regression matters, it has to be paid for somewhere other than the
direction tiers.

The tier weights matter little as long as they stay mild. 0.5/1.0/1.5 and
0.7/1.0/1.3 give byte-identical placements; 38 of 40 keys are also common to
0.3/1.0/2.0, which only differs by swapping the two heaviest keys (5.0: O and
I; 6.0: J and I) between the middle and ring centre slots. That one flip is
what makes the extreme setting worse on every measure that is not its own
objective, so the sensible reading is that the tier idea is robust and the
extreme weighting is not.

One caveat the numbers cannot cover: the tier ordering itself
(centre-edge easy, adjacent-edges medium, opposite-edges hard) is an
assumption about finger mechanics, the same kind as `FINGER_WEIGHT`. Part 2
of issue #28 goes looking for evidence for it in the Discord distillations.
""")
    print("""# Sanity checks

* **Flag off is byte-identical.** `python3 tools/thecore_svalboard.py` with no
  flags, before and after this branch's edit, gives identical stdout (sha1
  88d0a96359ec0c085f919885e6f93ec3a3da5155) and identical
  `thecore/svalboard-keymap.html` (sha1
  d0d74a38d255c2f014de1f21476d837a913fbcad, the same sha
  `thecore/coop-blend-report.md` records for the flag-off page).
* **Both co-op blends are byte-identical too.** `--coop-blend 0.5` (page sha1
  576d46051332880eb695531b6dcd3bc5a1c534d6) and `--coop-blend 0.5
  --coop-normalize` (892b70c18cb7e3b783f1df4b5a752dbd4d7d4670, the committed
  page) match their pre-edit stdout and HTML exactly.
* **No committed artifact was regenerated.** Every run above wrote the page to
  the worktree and was reverted with `git checkout --`; the branch changes
  only `tools/thecore_svalboard.py`, adds `tools/collision_report.py` and this
  report.
* **Determinism.** `--direction-tiers 0.5,1.0,1.5` run under
  `PYTHONHASHSEED=5` and `PYTHONHASHSEED=77` produced byte-identical stdout
  (sha1 391d4cf890a2a7413cb759bea47d15b29e96ba0a) and byte-identical HTML
  (089dc6d8152d76086b1b0a8259473e5d926bebc1). This report, generated under
  `PYTHONHASHSEED=5` and `PYTHONHASHSEED=99`, is byte-identical as well.
* **Script agrees with the CLI.** The tiered objective this report computes
  for the 0.5/1.0/1.5 1v1-only layouts (88.49 and 87.36) is the `final cost`
  line the tool itself prints under the same flag.
* **Placed counts unchanged.** 40 keys placed per file in every layout and
  every tier setting, and the tiered runs pass the tool's `EXPECTED_UNPLACED`
  guard unchanged.
""")


if __name__ == "__main__":
    main()
