#!/usr/bin/env python3
"""Measure what the co-op blends (issue #27) cost and buy.

Usage: python3 tools/coop_blend_report.py > thecore/coop-blend-report.md

For each hotkey file this recomputes three layouts with the exact functions
of tools/thecore_svalboard.py - 1v1-only, raw 50/50 blend, and normalized
50/50 blend (--coop-normalize) - then costs each fixed layout under the
1v1-only objective and under the co-op-only (equal-commander) objective via
thecore_svalboard.cost.
"""
import collections
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import thecore_svalboard as ts  # noqa: E402

W = 0.5


def layout(keys, load, pairs, slots):
    place, unplaced, _order, swaps, _ = ts.assign(dict(keys), load, pairs, slots, [])
    return place, unplaced, swaps


def total(place, slots, load, pairs):
    same, zones = ts.cost(place, slots, load, pairs)
    return same + zones


def finger_load(place, slots, load):
    out = collections.defaultdict(float)
    for k, i in place.items():
        out[slots[i]["finger"]] += load.get(k, 0.0)
    return out


def slot_name(slots, i):
    s = slots[i]
    return "%s %s (%s)" % (s["finger"], s["pos"], s["plane"])


def main():
    with open(os.path.join(ts.HERE, ts.SUMMARY), encoding="utf-8") as f:
        summary = json.load(f)
    with open(os.path.join(ts.HERE, ts.COOP), encoding="utf-8") as f:
        coop = json.load(f)
    slots = ts.build_slots()
    print("# What the co-op blends cost 1v1 play (issue #27)\n")
    print("Generated by `tools/coop_blend_report.py`. Three layouts per file:\n")
    print("* **1v1-only**: the layout of main, load and bigrams from the 187")
    print("  IEM replays alone.")
    print("* **raw 50/50**: each key's load = 0.5 x 1v1 per-minute rate +")
    print("  0.5 x co-op rate (equal-commander mean over 18 commanders, rates")
    print("  averaged, never pooled); bigram rates blend the same way. Co-op")
    print("  per-key rates total ~5x below 1v1 (bigram totals ~10x below),")
    print("  so this gives co-op well under half the influence.")
    print("* **normalized 50/50** (`--coop-normalize`, the committed layout on")
    print("  this branch): the co-op load dict is scaled by (sum of 1v1 key")
    print("  loads / sum of co-op key loads) and the co-op pair dict by the")
    print("  analogous pair-total ratio before the 50/50 mix, so the two")
    print("  corpora contribute equal total mass.\n")
    print("Constraints, finger weights, slot order and the optimizer are")
    print("unchanged throughout. Cost units are events per minute: same-finger")
    print("different-key transition rate (cross-plane at half weight) plus")
    print("load times slot difficulty. The headline is the normalized layout's")
    print("1v1 regression.\n")
    for name, rel in ts.FILES:
        keys = ts.read_file(os.path.join(ts.HERE, rel))
        ts.exclude(keys)
        l1, p1, _ = ts.replay_load(summary, rel)
        lc, pc = ts.coop_load(coop, rel)
        lraw, praw = ts.mix(l1, lc, W), ts.mix(p1, pc, W)
        lcn, pcn = ts.normalized(l1, p1, lc, pc)
        lnorm, pnorm = ts.mix(l1, lcn, W), ts.mix(p1, pcn, W)

        layouts = [("1v1-only", layout(keys, l1, p1, slots)[0]),
                   ("raw 50/50", layout(keys, lraw, praw, slots)[0]),
                   ("normalized 50/50", layout(keys, lnorm, pnorm, slots)[0])]
        assert len({len(pl) for _, pl in layouts}) == 1, "placed count changed"
        place1 = layouts[0][1]

        print("## %s\n" % name)
        print("Placed keys: %d in all three layouts.\n" % len(place1))
        print("| Objective | 1v1-only layout | raw 50/50 layout | normalized 50/50 layout |")
        print("| --- | --- | --- | --- |")
        for oname, lo, po in (("1v1-only", l1, p1),
                              ("co-op-only (equal-commander)", lc, pc)):
            base = total(place1, slots, lo, po)
            cells = []
            for _lname, pl in layouts:
                c = total(pl, slots, lo, po)
                cells.append("%.2f (%+.2f, %+.1f%%)"
                             % (c, c - base, 100.0 * (c - base) / base)
                             if pl is not place1 else "%.2f" % c)
            print("| %s | %s |" % (oname, " | ".join(cells)))
        print()
        print("| Under 1v1 data | 1v1-only | raw 50/50 | normalized 50/50 |")
        print("| --- | --- | --- | --- |")
        sf = [ts.cost(pl, slots, l1, p1)[0] for _, pl in layouts]
        print("| same-finger bigram rate /min | %s |"
              % " | ".join("%.2f" % v for v in sf))
        fl = [finger_load(pl, slots, l1) for _, pl in layouts]
        for f in ts.FINGERS:
            print("| %s load /min | %s |"
                  % (f, " | ".join("%.2f" % d[f] for d in fl)))
        print()
        placen = layouts[2][1]
        moved = sorted((k for k in place1 if place1[k] != placen[k]),
                       key=lambda k: -(l1.get(k, 0.0) + lc.get(k, 0.0)))
        print("Keys that moved, normalized 50/50 vs 1v1-only (%d):\n" % len(moved))
        print("| TheCore key | 1v1-only slot | normalized slot | 1v1 rate/min | co-op rate/min |")
        print("| --- | --- | --- | --- | --- |")
        for k in moved:
            print("| %s | %s | %s | %.2f | %.2f |"
                  % (ts.label(k), slot_name(slots, place1[k]),
                     slot_name(slots, placen[k]), l1.get(k, 0.0), lc.get(k, 0.0)))
        print()
    print("""## Sanity checks

* Default run (no flag) reproduces the committed main artifact: verified
  before this branch's regeneration. `python3 tools/thecore_svalboard.py`
  against commit c579161 reproduced `thecore/svalboard-keymap.html` except
  for one pre-existing drift: commit bd9fd12 added Mengsk to `COMMANDERS`
  in `tools/thecore_keymap.py` after the page was last generated, so the
  regenerated page adds the Mengsk filter button, shifts the two faction
  indices after it, and tags Terran-shared units with the Mengsk index.
  Parsing both pages' embedded DATA JSON, the slots, placement, stats and
  unplaced lists are identical for both files, and every entry is identical
  after remapping the shifted indices, apart from that added Mengsk index.
  The tool's stdout stayed byte-identical through every edit on this branch
  (sha1 of the flag-off page: d0d74a38d255c2f014de1f21476d837a913fbcad).
* Raw blend unchanged: `--coop-blend 0.5` without `--coop-normalize`
  produces stdout and HTML byte-identical to commit c244218 (sha1
  576d46051332880eb695531b6dcd3bc5a1c534d6).
* Normalized run is deterministic: `--coop-blend 0.5 --coop-normalize` run
  under `PYTHONHASHSEED=5` and `PYTHONHASHSEED=77` produced byte-identical
  `svalboard-keymap.html` (sha1 892b70c18cb7e3b783f1df4b5a752dbd4d7d4670)
  and byte-identical stdout.
* Placed keys unchanged: 40 per file in all three layouts (asserted above),
  and the normalized run's unplaced sets match `EXPECTED_UNPLACED` for both
  files; the guard runs unconditionally and passed.
""")


if __name__ == "__main__":
    main()
