#!/usr/bin/env python3
"""Measure what the 50/50 co-op blend (issue #27) costs and buys.

Usage: python3 tools/coop_blend_report.py > thecore/coop-blend-report.md

For each hotkey file this recomputes the 1v1-only layout and the 50/50
blended layout with the exact functions of tools/thecore_svalboard.py, then
costs each fixed layout under the 1v1-only objective and under the co-op-only
(equal-commander) objective via thecore_svalboard.cost.
"""
import collections
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import thecore_svalboard as ts  # noqa: E402

W = 0.5


def layout(keys, load, pairs, slots):
    place, unplaced, _order, swaps, _ = ts.assign(dict(keys), load, pairs, slots, [])
    return place, unplaced, swaps


def costs(place, slots, load, pairs):
    same, zones = ts.cost(place, slots, load, pairs)
    return same, zones, same + zones


def finger_load(place, slots, load):
    out = collections.defaultdict(float)
    for k, i in place.items():
        out[slots[i]["finger"]] += load.get(k, 0.0)
    return out


def slot_name(slots, i):
    s = slots[i]
    return "%s %s (%s)" % (s["finger"], s["pos"], s["plane"])


def main():
    with open(os.path.join(ts.HERE, ts.SUMMARY), encoding="utf-8") as f:
        summary = json.load(f)
    with open(os.path.join(ts.HERE, ts.COOP), encoding="utf-8") as f:
        coop = json.load(f)
    slots = ts.build_slots()
    print("# What the 50/50 co-op blend costs 1v1 play (issue #27)\n")
    print("Generated by `tools/coop_blend_report.py`. Blend: each key's load =")
    print("0.5 x 1v1 per-minute rate + 0.5 x co-op rate (equal-commander mean")
    print("over 18 commanders, rates averaged, never pooled); the bigram rates")
    print("that feed the same-finger cost blend the same way. Constraints,")
    print("finger weights, slot order and the optimizer are unchanged.\n")
    print("Cost units are events per minute: same-finger different-key")
    print("transition rate (cross-plane at half weight) plus load times slot")
    print("difficulty. The same-finger figures below are that first term.\n")
    for name, rel in ts.FILES:
        keys = ts.read_file(os.path.join(ts.HERE, rel))
        ts.exclude(keys)
        l1, p1, _ = ts.replay_load(summary, rel)
        lc, pc = ts.coop_load(coop, rel)
        lb, pb = ts.mix(l1, lc, W), ts.mix(p1, pc, W)

        place1, un1, _ = layout(keys, l1, p1, slots)
        placeb, unb, _ = layout(keys, lb, pb, slots)
        assert len(place1) == len(placeb), "placed-key count changed"

        print("## %s\n" % name)
        print("Placed keys: %d in both layouts.\n" % len(place1))
        print("| Objective | 1v1-only layout | blended layout | delta | delta % |")
        print("| --- | --- | --- | --- | --- |")
        for oname, lo, po in (("1v1-only", l1, p1),
                              ("co-op-only (equal-commander)", lc, pc)):
            c1 = costs(place1, slots, lo, po)[2]
            cb = costs(placeb, slots, lo, po)[2]
            print("| %s | %.2f | %.2f | %+.2f | %+.1f%% |"
                  % (oname, c1, cb, cb - c1, 100.0 * (cb - c1) / c1))
        print()
        s1 = costs(place1, slots, l1, p1)[0]
        sb = costs(placeb, slots, l1, p1)[0]
        print("Same-finger bigram rate under 1v1 data: %.2f/min (1v1-only"
              " layout) vs %.2f/min (blended layout).\n" % (s1, sb))
        f1 = finger_load(place1, slots, l1)
        fb = finger_load(placeb, slots, l1)
        print("| Finger | 1v1 load/min, 1v1-only layout | 1v1 load/min, blended layout |")
        print("| --- | --- | --- |")
        for f in ts.FINGERS:
            print("| %s | %.2f | %.2f |" % (f, f1[f], fb[f]))
        print()
        moved = sorted((k for k in place1 if place1[k] != placeb[k]),
                       key=lambda k: -(l1.get(k, 0.0) + lc.get(k, 0.0)))
        print("Keys that moved (%d):\n" % len(moved))
        print("| TheCore key | 1v1-only slot | blended slot | 1v1 rate/min | co-op rate/min |")
        print("| --- | --- | --- | --- | --- |")
        for k in moved:
            print("| %s | %s | %s | %.2f | %.2f |"
                  % (ts.label(k), slot_name(slots, place1[k]),
                     slot_name(slots, placeb[k]), l1.get(k, 0.0), lc.get(k, 0.0)))
        print()
    print("""## Sanity checks

* Default run (no flag) reproduces the committed main artifact: verified
  before this branch's regeneration. `python3 tools/thecore_svalboard.py`
  against commit c579161 reproduced `thecore/svalboard-keymap.html` except
  for one pre-existing drift: commit bd9fd12 added Mengsk to `COMMANDERS`
  in `tools/thecore_keymap.py` after the page was last generated, so the
  regenerated page adds the Mengsk filter button, shifts the two faction
  indices after it, and tags Terran-shared units with the Mengsk index.
  Parsing both pages' embedded DATA JSON, the slots, placement, stats and
  unplaced lists are identical for both files, and every entry is identical
  after remapping the shifted indices, apart from that added Mengsk index.
  The tool's stdout was byte-identical before and after adding the flag.
* Blended run is deterministic: `--coop-blend 0.5` run under
  `PYTHONHASHSEED=1` and `PYTHONHASHSEED=99` produced byte-identical
  `svalboard-keymap.html` (sha1 576d46051332880eb695531b6dcd3bc5a1c534d6)
  and byte-identical stdout.
* Placed keys unchanged: 40 per file in both layouts (asserted above), and
  the blended run's unplaced sets match `EXPECTED_UNPLACED` for both files.
""")


if __name__ == "__main__":
    main()
